spring.datasource.url=jdbc:h2:mem:eventos_academicos_consumidor;MODE=Oracle;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=false

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost/issuer
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost/jwks
spring.security.oauth2.resourceserver.jwt.audiences=test-audience

spring.rabbitmq.dynamic=false
spring.rabbitmq.listener.simple.auto-startup=false
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
app.rabbitmq.consumo-automatico=false
app.rabbitmq.queue=eventos-academicos-queue
app.rabbitmq.error-queue=eventos-academicos-error-queue
app.rabbitmq.exchange=eventos-academicos-exchange
app.rabbitmq.routing-key=evento.academico
app.rabbitmq.error-routing-key=evento.academico.error

management.health.rabbit.enabled=false
